import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";

export default function Home() {
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    window?.webkit?.messageHandlers?.hideNavbar?.postMessage("");
    window?.native?.hideNavbar();

    function apiSimulation() {
      setTimeout(() => {
        setIsLoading(false);
      }, 500);
    }

    // apiSimulation();

    const handleResize = () => {
      // Get the safe area values using JavaScript
      const safeAreaTop = window.safeAreaInsets?.top || 0;
      const safeAreaBottom = window.safeAreaInsets?.bottom || 0;

      // Update the CSS custom properties
      document.documentElement.style.setProperty(
        "--safe-area-inset-top",
        `${safeAreaTop}px`
      );
      document.documentElement.style.setProperty(
        "--safe-area-inset-bottom",
        `${safeAreaBottom}px`
      );
    };

    handleResize();

    // Listen to the resize event to handle orientation changes
    window.addEventListener("resize", handleResize);

    return () => {
      // Cleanup the event listener
      window.removeEventListener("resize", handleResize);
    };
  }, []);

  if (isLoading) {
    return (
      <div
        style={{
          width: "100vw",
          height: "100vh",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        Loading ...
      </div>
    );
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="initial-scale=1, viewport-fit=cover" />
      </Head>
      <div
        style={{
          height: "56px",
          width: "100%",
          display: "flex",
          alignItems: "center",
          background: "#0070f3",
          position: "fixed",
          top: "0",
          left: "0",
          padding: "20px",
          color: "white",
        }}
      >
        Home Page
      </div>

      <main className={styles.main} style={{ paddingTop: "128px" }}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
